id: P008086
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN7845
  title: བླ་མེད་རྡོ་རྗེ་ཐེག་པའི་ལམ་གྱི་སྔོན་འགྲོ་སོགས།
  author: ''
  volumes:
    26b4e7a1017446c09cdcee9582b970eb:
      image_group_id: I3CN7847
      title: ''
      volume_number: 1
      total_pages: 426
    1a47dbc4ca444ddf844868cd2781dc2e:
      image_group_id: I3CN7848
      title: ''
      volume_number: 2
      total_pages: 438
    8e7a7b35db0f442597bd97c802a3e529:
      image_group_id: I3CN7849
      title: ''
      volume_number: 3
      total_pages: 506
ebook_metadata:
  title: བླ་མེད་རྡོ་རྗེ་ཐེག་པའི་ལམ་གྱི་སྔོན་འགྲོ་སོགས།
  author: ''
  sku: P008086
  cover: cover.jpg
  layers:
  - pagination
