id: I4C2AC6FA
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T16:27:11+00:00'
last_modified: '2022-06-09T04:11:11.087062+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN7845
  title: བླ་མེད་རྡོ་རྗེ་ཐེག་པའི་ལམ་གྱི་སྔོན་འགྲོ་སོགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    AF57:
      image_group_id: I3CN7847
      title: Volume 1 of bla med rdo rje theg pa'i lam gyi sngon 'gro thar ba dang
        thams cad mkhyen pa'i lam gyi sgron me/
      total_pages: 426
      order: 1
      base_file: AF57.txt
    FFA1:
      image_group_id: I3CN7848
      title: Volume 2 of bla med rdo rje theg pa'i lam gyi sngon 'gro thar ba dang
        thams cad mkhyen pa'i lam gyi sgron me/
      total_pages: 438
      order: 2
      base_file: FFA1.txt
    60BF:
      image_group_id: I3CN7849
      title: Volume 3 of bla med rdo rje theg pa'i lam gyi sngon 'gro thar ba dang
        thams cad mkhyen pa'i lam gyi sgron me/
      total_pages: 506
      order: 3
      base_file: 60BF.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
