id: I4C2AC6FA
legacy_id: P008086
ocr_import_info:
  bdrc_scan_id: W3CN7845
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T16:23:34'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T15:52:10.449358+00:00'
last_modified: 2022-09-03 23:52:55.460640
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN7845
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN7845
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བླ་མེད་རྡོ་རྗེ་ཐེག་པའི་ལམ་གྱི་སྔོན་འགྲོ་སོགས།
  author: ཀུན་དགའ་དབང་ཕྱུག
statistics:
  ocr_word_mean_confidence_index: 0.9490008801119442
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I3CN7848:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN7848
      total_pages: 438
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I3CN7848.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9532458758756172
    legacy_id: v002
  I3CN7849:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN7849
      total_pages: 506
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I3CN7849.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9512578328600426
    legacy_id: v003
  I3CN7847:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN7847
      total_pages: 426
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN7847.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9411122594951938
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
